### ISSUE TITLE
CREATE INDEX CONCURRENTLY cannot be executed within a pipeline (on Postgresql)

### ISSUE THREAD

**Issue by kieranbenton** [erikbra/grate#334]
**Describe the bug**
Upon executing a set of migrations (i'm migrating from roundhouse to grate), when grate encounters a script that tries to create an index concurrently - it fails with this error:

```
Unhandled exception: grate.Exceptions.MigrationFailed: Migration failed due to errors:
 * 25001: CREATE INDEX CONCURRENTLY cannot be executed within a pipeline
 ---> Npgsql.PostgresException (0x80004005): 25001: CREATE INDEX CONCURRENTLY cannot be executed within a pipeline
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|233_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at grate.Migration.AnsiSqlDatabase.ExecuteNonQuery(DbConnection conn, String sql, Nullable`1 timeout) in /home/runner/work/grate/grate/grate/Migration/AnsiSqlDatabase.cs:line 664
   at grate.Migration.AnsiSqlDatabase.ExecuteNonQuery(DbConnection conn, String sql, Nullable`1 timeout) in /home/runner/work/grate/grate/grate/Migration/AnsiSqlDatabase.cs:line 664
   at grate.Migration.AnsiSqlDatabase.RunSql(String sql, ConnectionType connectionType, TransactionHandling transactionHandling) in /home/runner/work/grate/grate/grate/Migration/AnsiSqlDatabase.cs:line 464
   at grate.Migration.DbMigrator.RunTheActualSql(String sql, String scriptName, MigrationType migrationType, Int64 versionId, ConnectionType connectionType, TransactionHandling transactionHandling) in /home/runner/work/grate/grate/grate/Migration/DbMigrator.cs:line 285
   at grate.Migration.DbMigrator.RunTheActualSql(String sql, String scriptName, MigrationType migrationType, Int64 versionId, ConnectionType connectionType, TransactionHandling transactionHandling) in /home/runner/work/grate/grate/grate/Migration/DbMigrator.cs:line 306
   at grate.Migration.DbMigrator.<>c__DisplayClass28_0.<<RunSql>g__LogAndRunSql|0>d.MoveNext() in /home/runner/work/grate/grate/grate/Migration/DbMigrator.cs:line 93
--- End of stack trace from previous location ---
   at grate.Migration.DbMigrator.RunSql(String sql, String scriptName, MigrationType migrationType, Int64 versionId, GrateEnvironment environment, ConnectionType connectionType, TransactionHandling transactionHandling) in /home/runner/work/grate/grate/grate/Migration/DbMigrator.cs:line 152
   at grate.Migration.GrateMigrator.Process(DirectoryInfo root, MigrationsFolder folder, String changeDropFolder, Int64 versionId, ConnectionType connectionType, TransactionHandling transactionHandling) in /home/runner/work/grate/grate/grate/Migration/GrateMigrator.cs:line 331
   at grate.Migration.GrateMigrator.LogAndProcess(DirectoryInfo root, MigrationsFolder folder, String changeDropFolder, Int64 versionId, ConnectionType connectionType, TransactionHandling transactionHandling) in /home/runner/work/grate/grate/grate/Migration/GrateMigrator.cs:line 306
   at grate.Migration.GrateMigrator.Migrate() in /home/runner/work/grate/grate/grate/Migration/GrateMigrator.cs:line 124
  Exception data:
    Severity: ERROR
    SqlState: 25001
    MessageText: CREATE INDEX CONCURRENTLY cannot be executed within a pipeline
    File: xact.c
    Line: 3495
    Routine: PreventInTransactionBlock
   --- End of inner exception stack trace ---
   at grate.Migration.GrateMigrator.Migrate() in /home/runner/work/grate/grate/grate/Migration/GrateMigrator.cs:line 161
   at grate.Commands.MigrateCommand.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext() in /home/runner/work/grate/grate/grate/Commands/MigrateCommand.cs:line 48
--- End of stack trace from previous location ---
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**To Reproduce**
Use a script like this (```up/3100033_indexes_on_applied_tags.sql```):

```
DROP INDEX IF EXISTS IX_applied_tag CASCADE;
CREATE INDEX CONCURRENTLY IX_applied_tag ON public.applied_tag
	USING btree
	(
	  profile_id
	);

DROP INDEX IF EXISTS IX_applied_tag2 CASCADE;
CREATE INDEX CONCURRENTLY IX_applied_tag2 ON public.applied_tag
	USING btree
	(
	  source_id
	);
```

And execute against a postgres database with this commandline:

```
dotnet grate --sqlfilesdirectory="Scripts" --databasetype="postgresql" --connectionstring="Server=test;Port=5432;User Id=test;Password=test;Database=test" --environment="Development" --silent -ct=600
```

**Expected behavior**
The up migration script to complete successfully (as it does under roundhouse).

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Linux] Mac OS, Ventura 13.3.1 - ARM
 - Version: [e.g. 1.0.2] v1.5.0.0

**Additional context**
I've tried to find a way around this by disabling pipelining using some attribute in the connection string - but to no success, haven't found a way to do it.

I've even tried to find a way within NpgSql to disable pipelining, to no success either so far.

**Comment by kieranbenton** [comment]
I have tried adding: Multiplexing=false; to the connection string - but that has no effect. Any ideas?

**Comment by kieranbenton** [comment]
Possibly related to https://github.com/liquibase/liquibase/issues/3806?

**Comment by kieranbenton** [comment]
And https://github.com/DbUp/DbUp/issues/680 also. Looks like a change in behaviour in minor versions of postgres which is now affecting a lot of different migrations frameworks. See also https://www.postgresql.org/message-id/4139340.1676050723%40sss.pgh.pa.us where the original reporter of the liquibase issue is raising it on the postgres mailing list.

Not sure what the resolution is! I can't even downgrade right now as I can't find an appropriate ARM64 image to use...

**Comment by erikbra** [comment]
I'm no PostgreSQL expert, by all means, but according to https://github.com/liquibase/liquibase/issues/3806#issuecomment-1466374267 (which you refer to above), it looks like `CREATE INDEX CONCURRENTLY` cannot be run as a part of a batch, or a transaction (looks like that's a change in behaviour in the latest PostgreSQL minor version?). 

There doesn't seem to be an equivalent of SQL Server's `GO` as a batch separator in PostgreSQL's SQL tools (`GO` is not technically a SQL keyword, but an instruction to e.g. SQL Server Management Studio to execute the previous SQL statements as a batch, and create a new one). Oracle has something similar, in the `/` operator, which we fixed support for a couple of versions ago in grate. Googling points me to https://stackoverflow.com/a/30723618, which says `\g` is supported in the `psql` command-line editor, but that it is not frequently used. Do you guys use it a lot?

A suggestion would be to run grate in non-transactional mode, if that could work for you, either by turning it off for the entire run using `--transaction false`, or only for the INDEX folder, using a custom folder configuration, overriding only the indexes folder:

`grate --folders indexes=TransactionHandling:Autonomous`

This should override the transaction handling for only the indexes folder

(see https://erikbra.github.io/grate/folder-configuration/#specifying-a-custom-list-of-folders)

**Comment by kieranbenton** [comment]
Thanks @erikbra - that is a useful to know workaround to use non-transactional mode, I wasn't aware of that, and nice way to make it only disable for specific folders (although that won't work for our legacy setup unfortunately I think).

I think this isn't actually to do with transactions though (at least not directly) - its to do with the new pipelining connections introduced into postgres + clients I believe? I'm not exactly authoritative on this, but I have been tracking the changes as it affects our production pgbouncer setup.

Its called pipelining on the server: https://www.postgresql.org/docs/current/libpq-pipeline-mode.html

And multiplexing in npgsql (which I think is what grate uses?): https://github.com/npgsql/npgsql/issues/1982

Now, I suppose the solution might be to disable pipelining for grate (which I believe would make sense as its not trying to make masses of connections/queries in parallel) - but I'm not actually sure theres a way to do that in npgsql (I experimented with a few different query strings but nothing worked).

Does that make sense?

**Comment by erikbra** [comment]
Hi again, @kieranbenton  - it looks like it's not really possible to turn the pipelining mode off. It looks to be enables by default if there are multiple batches in a separate SQL command sent to PostgreSQL. **However**, there is a batch-splitting feature in grate (inherited from RoundhousE, of course), that splits scripts with multiple statements in them into multiple commands to the server. This has only ever been working (properly) for SQL server. I have tried to make a fix to the batch splitting in PostgreSQL. It seems to solve your particular use case, but I don't use PostgreSQL a lot, and I'm a bit concerned about unintended side effects.

Do you have a large-ish PostgreSQL script suite to test this on? Could you do so if I build a test version for you?

Here is the PR with the fix: https://github.com/erikbra/grate/pull/345

**Comment by kieranbenton** [comment]
Sorry, late to respond - but to confirm, this appears to have solved the issues we were having - we need to go through a full release cycle to be sure but its not regressed anything for us yet.

**Comment by erikbra** [comment]
Lovely, @kieranbenton . I have full respect for taking a while to reply. I struggle with this myself, and in periods it's difficult to prioritise grate, as I don't get paid for working on it, and I **do** get paid for my day-job ;)
