### ISSUE TITLE
Azure SQL migrations with Managed Identity not working after 1.3.0

### ISSUE THREAD

**Issue by NicolaiPetri** [erikbra/grate#340]
**Describe the bug**
Running migrations fails with:
Unhandled exception: System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
It seems like after initial db connect (it reads current version) something messes up connection string.

**To Reproduce**
Run migrations on Azure SQL with grate version 1.4.0 or 1.5.0 
1.3.0 works as expected.

**Expected behavior**
Migrations should run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows server 2022
 - Version: grate 1.4.0 + 1.5.0

**Additional context**

Stack trace:
Looking for AlterDatabase scripts in "Infrastructure\alterDatabase".
--------------------------------------------------------------------------------
Unhandled exception: System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)
   at grate.Migration.SqlServerDatabase.GetSqlConnection(String connectionString) in /home/runner/work/grate/grate/grate/Migration/SqlServerDatabase.cs:line 27
   at grate.Migration.AnsiSqlDatabase.get_AdminConnection() in /home/runner/work/grate/grate/grate/Migration/AnsiSqlDatabase.cs:line 71
   at grate.Migration.AnsiSqlDatabase.OpenAdminConnection() in /home/runner/work/grate/grate/grate/Migration/AnsiSqlDatabase.cs:line 160
   at grate.Migration.GrateMigrator.EnsureConnectionIsOpen(ConnectionType connectionType) in /home/runner/work/grate/grate/grate/Migration/GrateMigrator.cs:line 190
   at grate.Migration.GrateMigrator.Process(DirectoryInfo root, MigrationsFolder folder, String changeDropFolder, Int64 versionId, ConnectionType connectionType, TransactionHandling transactionHandling) in /home/runner/work/grate/grate/grate/Migration/GrateMigrator.cs:line 316
   at grate.Migration.GrateMigrator.LogAndProcess(DirectoryInfo root, MigrationsFolder folder, String changeDropFolder, Int64 versionId, ConnectionType connectionType, TransactionHandling transactionHandling) in /home/runner/work/grate/grate/grate/Migration/GrateMigrator.cs:line 306
   at grate.Migration.GrateMigrator.Migrate() in /home/runner/work/grate/grate/grate/Migration/GrateMigrator.cs:line 131
   at grate.Commands.MigrateCommand.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext() in /home/runner/work/grate/grate/grate/Commands/MigrateCommand.cs:line 48
--- End of stack trace from previous location ---
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by erikbra** [comment]
Hi, @NicolaiPetri , du you have an (anonymized) example of a connection string that doesn't work?

**Comment by jbogard** [comment]
FYI managed identities are working for us just fine. Connection string:

```
Server=<server>,1433;Initial Catalog=<db>;Persist Security Info=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Authentication=Active Directory Default;
```

We're using a system-assigned managed identity in a VM scale set for our Azure Dev Ops build agents. We haven't tried using a user-assigned managed identity, but if we did we'd just add `User ID=<principal ID>` and it should also work.

**Comment by erikbra** [comment]
Thanks for confirming that it does work, @jbogard. This is my experience as well, and in the new Microsoft SqlClient library, SQL authentication with integrated credentials very often "just work". It's a bit creative in that it tries a _lot_ of different authentication mechanisms, and the fallthrough to the next working one is not always brilliant. So, @NicolaiPetri, if you have problems with "Active Directory Default", you can try explicitly using one of the other mechanisms explicitly, as mentioned here:

https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet

E.g. "Active Directory Integrated", "Active Directory Interactive", etc.
