### ISSUE TITLE
Scripts using postgresql dollar-quoted strings fail in version 1.5.1

### ISSUE THREAD

**Issue by koenekelschot** [erikbra/grate#357]
**Describe the bug**
When using version 1.5.1 scripts containing dollar-quoted strings fail with an error. Version 1.5.0 works fine, so I suspect it has something to do with [this change](https://github.com/erikbra/grate/pull/345).

The error:
```
Unhandled exception: grate.Exceptions.MigrationFailed: Migration failed due to errors:
 * 42601: unterminated dollar-quoted string at or near "$$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.schemata
        WHERE schema_name = 'public'
    )
    THEN
        GRANT USAGE ON SCHEMA public TO username"

POSITION: 4
 ---> Npgsql.PostgresException (0x80004005): 42601: unterminated dollar-quoted string at or near "$$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.schemata
        WHERE schema_name = 'public'
    )
    THEN
        GRANT USAGE ON SCHEMA public TO username"

POSITION: 4
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|233_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at grate.Migration.AnsiSqlDatabase.ExecuteNonQuery(DbConnection conn, String sql, Nullable`1 timeout)
   at grate.Migration.AnsiSqlDatabase.ExecuteNonQuery(DbConnection conn, String sql, Nullable`1 timeout)
   at grate.Migration.AnsiSqlDatabase.RunSql(String sql, ConnectionType connectionType, TransactionHandling transactionHandling)
   at grate.Migration.DbMigrator.RunTheActualSql(String sql, String scriptName, MigrationType migrationType, Int64 versionId, ConnectionType connectionType, TransactionHandling transactionHandling)
   at grate.Migration.DbMigrator.RunTheActualSql(String sql, String scriptName, MigrationType migrationType, Int64 versionId, ConnectionType connectionType, TransactionHandling transactionHandling)
   at grate.Migration.DbMigrator.<>c__DisplayClass28_0.<<RunSql>g__LogAndRunSql|0>d.MoveNext()
--- End of stack trace from previous location ---
   at grate.Migration.DbMigrator.RunSql(String sql, String scriptName, MigrationType migrationType, Int64 versionId, GrateEnvironment environment, ConnectionType connectionType, TransactionHandling transactionHandling)
   at grate.Migration.GrateMigrator.Process(DirectoryInfo root, MigrationsFolder folder, String changeDropFolder, Int64 versionId, ConnectionType connectionType, TransactionHandling transactionHandling)
   at grate.Migration.GrateMigrator.LogAndProcess(DirectoryInfo root, MigrationsFolder folder, String changeDropFolder, Int64 versionId, ConnectionType connectionType, TransactionHandling transactionHandling)
   at grate.Migration.GrateMigrator.Migrate()
  Exception data:
    Severity: ERROR
    SqlState: 42601
    MessageText: unterminated dollar-quoted string at or near "$$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.schemata
        WHERE schema_name = 'public'
    )
    THEN
        GRANT USAGE ON SCHEMA public TO username"
    Position: 4
    File: scan.l
    Line: 1181
    Routine: scanner_yyerror
   --- End of inner exception stack trace ---
   at grate.Migration.GrateMigrator.Migrate()
   at grate.Commands.MigrateCommand.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**To Reproduce**
Use Grate 1.5.1 with a script like below (`permissions/username.sql`) and execute it against a postgresql database:
```
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.schemata
        WHERE schema_name = 'public'
    )
    THEN
        GRANT USAGE ON SCHEMA public TO username;
        GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO username;
        GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA public TO username;
    END IF;
END
$$
```

**Expected behavior**
The permission script to complete successfully (as it does under Grate 1.5.0)

**Desktop (please complete the following information):**
 - OS: Dockerfile (erikbra/grate:1.5.1)
 - Version: 1.5.1

**Comment by Westat-Transportation** [comment]
I am seeing the same error while trying to run an `Up` script created using `pg_dump` that includes dollar-quoted strings.  Interestingly enough I get another error when trying to use a script created by `pg_dump` with the `--disable-dollar-quoting` option.

**Comment by Westat-Transportation** [comment]
Reverting to grate 1.5.0 makes it so the dollar-quoted dump restores successfully.

**Comment by koenekelschot** [comment]
@Westat-Transportation is there any chance you can share the script with dollar quoting disabled? I could use that as a test case for my proposed fix.

**Comment by Westat-Transportation** [comment]
Sure, can I send it privately?  It's for a LOB system db and its schema is proprietary.

**Comment by Westat-Transportation** [comment]
@koenekelschot sent repro file via email.

**Comment by Westat-Transportation** [comment]
Folks, gave grate 1.5.2 a go today and hit similar crashes $$ terminated functions.  The error message mentioned a line where $$ was declared and immediately followed by another keyword:
```
Error running script "001-db_schema.sql": 42601: unterminated dollar-quoted string at or near "$$TRUNCATE TABLE gis.tps_tbw_gps_places"
```

So I edited the .sql file and made sure all of the `AS $$` declarations were followed by a line break with the next statement on the next line.  When I did that I got another error:

```
Error running script "001-db_schema.sql": 42601: unterminated quoted string at or near "'"
```

Went back to 1.5.0 and it worked with both versions of the file `001-db_schema.sql`.  So I think there may still be room for improvement in parsing files using $$ termination.  I will email the git repo which is running these separately -- that will allow you to see my edits from this morning.

**Comment by Westat-Transportation** [comment]
I am doing some local debugging against my files here.  Will update this later if I can make it work.

**Comment by Westat-Transportation** [comment]
No luck, my attempts at tweaking the RegEx expressions did not work.  I modified the code to write out the parsed statements so I can see where it was on the file when it bombed and found out that the following conditions were problematic for it:

- semicolons inside single quotes as part of text concatenation expressions (`col_name || '; '::text)`.
- DO code blocks delimited by `$do$`

**Comment by Westat-Transportation** [comment]
@erikbra and @koenekelschot, I decided to take my modified code which records to a separate file the actual split statements that were sent to the db (just now realized I could have change verbosity, oh well) and bring over what the RegExes were in 1.5.0 and realized that grate was not really splitting PostgreSQL statements back in 1.5.0.  The whole contents of a database dump were being sent to the server via npgsql. 

Given the difficulties we are having to get this splitting to work in 1.5.1 and 1.5.2 what about introducing a CLI switch which basically turns that off on grate?  I realize this mode would not work for cases like bugs/334-pgsql-concurrent.  But it would allow folks like me to keep using the latest until a better approach for statement splitting can be developed.

Just a thought.
